replicaCount: 80

image:
  registry: docker.io
  organization: antsinmyey3sjohnson
  repository: hazeltest
  # 0.5.4
  digest: 2c7bd81af6fdff80fe6f8ad46aa41ec52012ac748628d24dd9132117beccd98a
  pullPolicy: IfNotPresent

httpPort: 8080
resources:
  requests:
    cpu: "100m"
    memory: "32Mi"
  limits:
    cpu: "200m"
    memory: "64Mi"

startupArgs:
  - "-config-file=/data/config/custom-config.yaml"
  - "-use-unisocket-client=false"

env:
  # Name of the Hazelcast cluster to connect to -- usually configured in Hazelcast by means of the "hazelcast.cluster-name" property
  hzCluster: "hazelcastplatform"
  # Can be IP addresses or Kubernetes services names
  # Accepts multiple comma-separated values ("service1,service2,service3")
  hzMembers: "hazelcastimdg.hazelcastplatform.svc.cluster.local:5701"
  # Set this to TRACE if you want to make the people running your IT department's logging platform very angry
  logLevel: INFO

config:
  # For documentation on these properties, please refer to <repo root>/client/defaultConfig.yaml
  queuetests:
    tweets:
      enabled: true
      numQueues: 10
      appendQueueIndexToQueueName: true
      appendClientIdToQueueName: true
      queuePrefix:
        enabled: true
        prefix: "ht_"
      putConfig:
        enabled: true
        numRuns: 10000
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: false
            durationMs: 2000
          betweenActionBatches:
            enabled: true
            durationMs: 1000
          betweenRuns:
            enabled: true
            durationMs: 2000
      pollConfig:
        enabled: true
        numRuns: 10000
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: true
            durationMs: 2000
          betweenActionBatches:
            enabled: true
            durationMs: 1000
          betweenRuns:
            enabled: true
            durationMs: 2000
    load:
      enabled: true
      numQueues: 10
      numLoadEntries: 5000
      payloadSizeBytes: 100
      appendQueueIndexToQueueName: true
      appendClientIdToQueueName: true
      queuePrefix:
        enabled: true
        prefix: "ht_"
      putConfig:
        enabled: true
        numRuns: 10000
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: false
            durationMs: 2000
          betweenActionBatches:
            enabled: true
            durationMs: 1333
          betweenRuns:
            enabled: true
            durationMs: 870
      pollConfig:
        enabled: true
        numRuns: 10000
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: true
            durationMs: 2000
          betweenActionBatches:
            enabled: true
            durationMs: 1333
          betweenRuns:
            enabled: true
            durationMs: 870

  maptests:
    pokedex:
      enabled: true
      numMaps: 20
      appendMapIndexToMapName: true
      appendClientIdToMapName: true
      numRuns: 10000
      mapPrefix:
        enabled: true
        prefix: "ht_"
      sleeps:
        betweenActionBatches:
          enabled: true
          durationMs: 500
        betweenRuns:
          enabled: true
          durationMs: 1000
    load:
      enabled: true
      numMaps: 20
      numEntriesPerMap: 50000
      payloadSizeBytes: 100000
      appendMapIndexToMapName: true
      appendClientIdToMapName: true
      numRuns: 10000
      mapPrefix:
        enabled: true
        prefix: "ht_"
      sleeps:
        betweenActionBatches:
          enabled: true
          durationMs: 200
        betweenRuns:
          enabled: true
          durationMs: 1300