platform:
  deploy: true
  service:
    type: NodePort
    port: 5701
  cluster:
    logging:
      level: INFO
    members:
      image: hazelcast/hazelcast:5.2.1
      imagePullPolicy: IfNotPresent
      count: 3
      ports:
        member: 5701
        metrics: 8080
      gracefulShutDown:
        maxWaitSeconds: 600
      containerResources:
        requests:
          cpu: "2"
          memory: "6G"
        limits:
          cpu: "2"
          memory: "6G"
      jvmResources:
        xmx: 4800m
        xms: 4800m
      liveness:
        initialDelaySeconds: 15
        periodSeconds: 10
      readiness:
        initialDelaySeconds: 30
        periodSeconds: 10
  config:
    hazelcast:
      metrics:
        enabled: true
        collection-frequency-seconds: 60
      jet:
        enabled: true
      cluster-name: "hazelcastplatform"
      properties:
        hazelcast.heartbeat.interval.seconds: 10
        hazelcast.jmx: true
        hazelcast.logging.type: log4j2
      network:
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-port: 5701
      # https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml
      map:
        default:
          backup-count: 0
          max-idle-seconds: 5
          in-memory-format: BINARY
          eviction:
            eviction-policy: LRU
            max-size-policy: FREE_HEAP_PERCENTAGE
            size: 50
        ht_*:
          backup-count: 1
          read-backup-date: true
          max-idle-seconds: 600
          in-memory-format: BINARY
          eviction:
            eviction-policy: LRU
            max-size-policy: FREE_HEAP_PERCENTAGE
            size: 15
        ht_no_backup_*:
          backup-count: 0
          max-idle-seconds: 600
          in-memory-format: BINARY
          eviction:
            eviction-policy: LRU
            max-size-policy: FREE_HEAP_PERCENTAGE
            size: 15

mancenter:
  deploy: true
  service:
    type: NodePort
    port: 8080
  instance:
    image: hazelcast/management-center:5.1.3
    imagePullPolicy: IfNotPresent
    # 'enabled' vs. 'enable' is not a typo, those properties are actually called like so
    javaOpts: "-Dhazelcast.mc.metrics.persistence.enabled=false -Dhazelcast.mc.healthCheck.enable=true"
    ports:
      web:
        name: web
        port: 8080
      health:
        name: health
        port: 8081
    liveness:
      path: /health
    readiness:
      path: /health
    resources:
      requests:
        cpu: "500m"
        memory: "2G"
      limits:
        cpu: "500m"
        memory: "2G"
