replicaCount: 1

image:
  registry: docker.io
  organization: antsinmyey3sjohnson
  repository: hazeltest
  # 0.8.0
  digest: 61fc02b32a17b2410abf5b4d68451c7d3a87490503ea2cf7661da1f54f70d54d
  pullPolicy: IfNotPresent

httpPort: 8080
resources:
  requests:
    cpu: "1"
    memory: "200Mi"
  limits:
    cpu: "2"
    memory: "400Mi"

startupArgs:
  - "-config-file=/data/config/custom-config.yaml"
  - "-use-unisocket-client=false"

env:
  # Name of the Hazelcast cluster to connect to -- usually configured in Hazelcast by means of the "hazelcast.cluster-name" property
  hzCluster: "hazelcastplatform"
  # Can be IP addresses or Kubernetes services names
  # Accepts multiple comma-separated values ("service1,service2,service3")
  hzMembers: "hazelcastimdg.hazelcastplatform.svc.cluster.local:5701"
  # Set this to TRACE if you want to make the people running your IT department's logging platform very angry
  logLevel: INFO

features:
  # Only set this to false if no chaos monkey runs with the 'k8sInCluster' hazelcast member access mode
  # (The reason the template doesn't evaluate this directly is because a user might rely on one of the
  # built-in config files to configure chaos monkeys and not provide a custom config in this yaml file)
  useDeletePodsServiceAccount: true

config:
  # For documentation on these properties, please refer to <repo root>/client/defaultConfig.yaml
  chaosMonkeys:
    memberKiller:
      enabled: true
      numRuns: 500
      chaosProbability: 1.0
      memberAccess:
        mode: k8sInCluster
        targetOnlyActive: true
        k8sInCluster:
          labelSelector: app.kubernetes.io/name=hazelcastimdg
      sleep:
        enabled: true
        durationSeconds: 60
        enableRandomness: false
      memberGrace:
        enabled: false
        durationSeconds: 600
        enableRandomness: false

  queueTests:
    tweets:
      enabled: false
    load:
      enabled: false

  mapTests:
    pokedex:
      enabled: true
      numMaps: 10
      appendMapIndexToMapName: true
      appendClientIdToMapName: false
      numRuns: 10000
      mapPrefix:
        enabled: true
        prefix: "ht_no_backup_"
      sleeps:
        betweenActionBatches:
          enabled: true
          durationMs: 500
          enableRandomness: true
        betweenRuns:
          enabled: true
          durationMs: 1000
          enableRandomness: true
    load:
      enabled: true
      numMaps: 10
      numEntriesPerMap: 100
      payloadSizeBytes: 2000000
      appendMapIndexToMapName: true
      appendClientIdToMapName: false
      numRuns: 10000
      mapPrefix:
        enabled: true
        prefix: "ht_"
      sleeps:
        betweenActionBatches:
          enabled: true
          durationMs: 200
          enableRandomness: true
        betweenRuns:
          enabled: true
          durationMs: 1300
          enableRandomness: true