# Define base image
FROM python:alpine3.12

# Add Python script to root directory within image
ADD hello_container_service.py /

# Run Python script
CMD ["python", "-u", "./hello_container_service.py"]
