replicaCount: 10
image:
  tag: 0.16.3
  digest: 8e541dd70d059cee0572c186fbbbfd05ff276c9f0edbf59ed71cc482bd94757f
resources:
  requests:
    cpu: "1"
    memory: "40M"
  limits:
    cpu: "2"
    memory: "80M"
config:
  chaosMonkeys:
    memberKiller:
      enabled: false
  stateCleaners:
    queues:
      enabled: false
  queueTests:
    tweets:
      enabled: false
    load:
      enabled: false
  mapTests:
    pokedex:
      enabled: false
    load:
      enabled: true
      numMaps: 30
      numEntriesPerMap: 12000
      # Will increase number of maps from 30 to 300
      # (load dimension 3)
      appendClientIdToMapName: true
      numRuns: 1
      payload:
        fixedSize:
          enabled: false
        variableSize:
          enabled: true
          lowerBoundaryBytes: 1000
          upperBoundaryBytes: 70000
      mapPrefix:
        enabled: true
        prefix: "ht_"
      testLoop:
        type: batch
        batch:
          sleeps:
            afterBatchAction:
              enabled: false
            afterActionBatch:
              enabled: false