replicaCount: 1
image:
  tag: 0.16.3-dev7
  digest: f577bace2857d1957dd23c57d2dd8c7e81ac00b3a9bece810a9d6236f6f7dba7
resources:
  requests:
    cpu: "1"
    memory: "25M"
  limits:
    cpu: "2"
    memory: "50M"
config:
  chaosMonkeys:
    memberKiller:
      enabled: false
  stateCleaners:
    queues:
      enabled: false
  queueTests:
    tweets:
      enabled: false
    load:
      enabled: false
  mapTests:
    pokedex:
      enabled: false
    load:
      enabled: true
      # Goal: Exhaust 48gb of memory as quickly as possible
      # 30 maps --> Each map needs to write 1,6gb --> 16.000mb or 16.000.000kb
      # Given item size: 2kb
      # Therefore items per map: 800.000
      # But: "ht_" pattern configured with 1 backup --> We need to occupy only
      # half of 48gb with primary entries --> items per map: 400.000
      numMaps: 30
      numEntriesPerMap: 400000
      numRuns: 1
      payload:
        fixedSize:
          enabled: true
          sizeBytes: 2000
        variableSize:
          enabled: false
      mapPrefix:
        enabled: true
        prefix: "ht_"
      testLoop:
        type: batch
        batch:
          sleeps:
            afterBatchAction:
              enabled: false
            afterActionBatch:
              enabled: false