# Load dimension 4
replicaCount: 10
image:
  tag: 0.16.3
  digest: 8e541dd70d059cee0572c186fbbbfd05ff276c9f0edbf59ed71cc482bd94757f
resources:
  requests:
    cpu: "1"
    memory: "25M"
  limits:
    cpu: "2"
    memory: "50M"
config:
  chaosMonkeys:
    memberKiller:
      enabled: false
  stateCleaners:
    queues:
      enabled: false
  queueTests:
    tweets:
      enabled: false
    load:
      enabled: false
  mapTests:
    pokedex:
      enabled: false
    load:
      enabled: true
      numMaps: 30
      # Now 10 replicas, so decrease number of entries per map to 40.000
      # (load dimension 1)
      numEntriesPerMap: 40000
      numRuns: 1
      payload:
        fixedSize:
          enabled: true
          sizeBytes: 2000
        variableSize:
          enabled: false
      mapPrefix:
        enabled: true
        prefix: "ht_"
      testLoop:
        type: batch
        batch:
          sleeps:
            afterBatchAction:
              enabled: false
            afterActionBatch:
              enabled: false