replicaCount: 10
image:
  tag: 0.16.3-dev5
  digest: 615a97f40ddb2f70c1e33cd5e431d4be083382d01a8bcf2812759aab53c84550
resources:
  requests:
    cpu: "1"
    memory: "40M"
  limits:
    cpu: "2"
    memory: "80M"
config:
  chaosMonkeys:
    memberKiller:
      enabled: false
  stateCleaners:
    queues:
      enabled: false
  queueTests:
    tweets:
      enabled: false
    load:
      enabled: false
  mapTests:
    pokedex:
      enabled: false
    load:
      enabled: true
      numMaps: 30
      # Decrease number of items per map (load dimension 1) as a result
      # of having significantly increased payload size
      numEntriesPerMap: 12000
      numRuns: 1
      payload:
        fixedSize:
          enabled: false
        variableSize:
          # Load dimension 2
          enabled: true
          lowerBoundaryBytes: 1000
          upperBoundaryBytes: 70000
      mapPrefix:
        enabled: true
        prefix: "ht_"
      testLoop:
        type: batch
        batch:
          sleeps:
            afterBatchAction:
              enabled: false
            afterActionBatch:
              enabled: false