platform:
  deploy: true
  service:
    type: NodePort
    port: 5701
  cluster:
    logging:
      level: INFO
    members:
      image: hazelcast/hazelcast:5.1.1
      imagePullPolicy: IfNotPresent
      count: 3
      ports:
        member: 5701
        metrics: 8080
      gracefulShutDown:
        maxWaitSeconds: 60
      containerResources:
        requests:
          cpu: "1"
          memory: "3G"
        limits:
          cpu: "2"
          memory: "3G"
      jvmResources:
        xmx: 2500m
        xms: 2500m
      liveness:
        initialDelaySeconds: 15
        periodSeconds: 10
      readiness:
        initialDelaySeconds: 30
        periodSeconds: 10
  config:
    hazelcast:
      jet:
        enabled: true
      cluster-name: "hazelcastplatform"
      properties:
        hazelcast.heartbeat.interval.seconds: 10
        hazelcast.jmx: true
        hazelcast.logging.type: log4j2
      network:
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-port: 5701
      map:
        # Default configuration is pretty restrictive to protect cluster from misbehaving clients
        default:
            backup-count: 0
            # Map entries will be expired after 5 seconds of inactivity (neither read nor write)
            max-idle-seconds: 5
            in-memory-format: BINARY
        # Assumption: A client application uses maps starting with `ht_`
        ht_*:
            backup-count: 1
            # Keep entries around for ten minutes
            max-idle-seconds: 600
            in-memory-format: BINARY

mancenter:
  deploy: true
  service:
    type: NodePort
    port: 8080
  instance:
    image: hazelcast/management-center:5.1.3
    imagePullPolicy: IfNotPresent
    # 'enabled' vs. 'enable' is not a typo, those properties are actually called like so
    javaOpts: "-Dhazelcast.mc.metrics.persistence.enabled=false -Dhazelcast.mc.healthCheck.enable=true"
    ports:
      web:
        name: web
        port: 8080
      health:
        name: health
        port: 8081
    liveness:
      path: /health
    readiness:
      path: /health
    resources:
      requests:
        cpu: "500m"
        memory: "4G"
      limits:
        cpu: "1"
        memory: "4G"
