apiVersion: v1
kind: Namespace
metadata:
  name: simple-label-demonstration
---
apiVersion: v1
kind: Pod
metadata:
  name: persistence-app-instance-1
  namespace: simple-label-demonstration
  labels:
    app.kubernetes.io/name: persistence-app
    group: persistence
    user: dave
spec:
  containers:
  - name: hello-service
    image: antsinmyey3sjohnson/hello-container-service:1.0
    resources:
      limits: 
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: persistence-app-instance-2
  namespace: simple-label-demonstration
  labels:
    app.kubernetes.io/name: persistence-app
    group: persistence
    user: mary
spec:
  containers:
  - name: hello-service
    image: antsinmyey3sjohnson/hello-container-service:1.0
    resources:
      limits: 
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: another-persistence-app-instance-1
  namespace: simple-label-demonstration
  labels:
    app.kubernetes.io/name: another-persistence-app
    group: persistence
    user: dave
spec:
  containers:
  - name: hello-service
    image: antsinmyey3sjohnson/hello-container-service:1.0
    resources:
      limits: 
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: search-app-instance-1
  namespace: simple-label-demonstration
  labels:
    app.kubernetes.io/name: search-app
    group: search
    user: mary
spec:
  containers:
  - name: hello-service
    image: antsinmyey3sjohnson/hello-container-service:1.0
    resources:
      limits: 
        cpu: 100m
        memory: 128Mi


