apiVersion: v1
kind: Namespace
metadata:
  name: pod-adoption-example
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: adopting-replicaset
  namespace: pod-adoption-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
      - name: hello-service
        image: antsinmyey3sjohnson/hello-container-service@sha256:e9de17b4fbfc6a1f52d07609e285dab3818412016200f189c68e441bf23effb3
        ports:
        - name: http
          containerPort: 8081
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: adopted-pod
  namespace: pod-adoption-example
  labels:
    app: hello-service
spec:
  containers:
    - name: hello-service
      image: antsinmyey3sjohnson/hello-container-service@sha256:e9de17b4fbfc6a1f52d07609e285dab3818412016200f189c68e441bf23effb3
      ports:
      - name: http
        containerPort: 8081
      resources:
        limits:
          cpu: 200m
          memory: 128Mi