apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: hello-pod
spec:
  containers:
  - name: hello-container-service
    image: antsinmyey3sjohnson/hello-container-service:1.0
    ports:
      - containerPort: 8081

