apiVersion: v1
kind: Pod
metadata:
  name: print-pod-info
  labels:
    name: print-pod-info
spec:
  containers:
  - name: client-container
    image: k8s.gcr.io/busybox
    command: ["sh", "-c"]   
    args:
      - while true; do
          if [[ -n $POD_IP ]]; then
            echo -en '\n\nPod IP:\n'; echo -n $POD_IP;
          fi;
          if [[ -e /etc/podinfo/labels ]]; then
            echo -en '\n\nLabels:\n'; cat /etc/podinfo/labels;
          fi;
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\nAnnotations:\n'; cat /etc/podinfo/annotations;
          fi;
          sleep 10;
        done;
    env:
      - name: POD_IP
        valueFrom:
            fieldRef:
              fieldPath: status.podIP
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /etc/podinfo
        name: podinfo
  volumes:
    - name: podinfo
      downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
  terminationGracePeriodSeconds: 0
