replicaCount: 10

image:
  registry: docker.io
  organization: antsinmyey3sjohnson
  repository: hazeltest
  # 0.7.0
  digest: 9f2ab556c5c31e5e60ff84cbd6a107922c3a3be2c1cace4825af78347f14d4d6
  pullPolicy: IfNotPresent

httpPort: 8080
resources:
  requests:
    cpu: "500m"
    memory: "128Mi"
  limits:
    cpu: "1"
    memory: "256Mi"

startupArgs:
  - "-config-file=/data/config/custom-config.yaml"
  - "-use-unisocket-client=false"

env:
  # Name of the Hazelcast cluster to connect to -- usually configured in Hazelcast by means of the "hazelcast.cluster-name" property
  hzCluster: "hazelcastplatform"
  # Can be IP addresses or Kubernetes services names
  # Accepts multiple comma-separated values ("service1,service2,service3")
  hzMembers: "hazelcastimdg.hazelcastplatform.svc.cluster.local:5701"
  # Set this to TRACE if you want to make the people running your IT department's logging platform very angry
  logLevel: INFO

config:
  # For documentation on these properties, please refer to <repo root>/client/config/defaultConfig.yaml
  queuetests:
    tweets:
      enabled: false
      numQueues: 5
      appendQueueIndexToQueueName: false
      appendClientIdToQueueName: false
      queuePrefix:
        enabled: true
        prefix: "app1_"
      putConfig:
        enabled: true
        numRuns: 500
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: false
            durationMs: 2000
            enableRandomness: true
          betweenActionBatches:
            enabled: true
            durationMs: 2000
            enableRandomness: true
          betweenRuns:
            enabled: true
            durationMs: 5000
            enableRandomness: true
      pollConfig:
        enabled: true
        numRuns: 500
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: true
            durationMs: 12500
            enableRandomness: true
          betweenActionBatches:
            enabled: true
            durationMs: 2000
            enableRandomness: true
          betweenRuns:
            enabled: true
            durationMs: 5000
            enableRandomness: true
    load:
      enabled: false
      numQueues: 10
      numLoadEntries: 5000
      payloadSizeBytes: 5000
      appendQueueIndexToQueueName: false
      appendClientIdToQueueName: false
      queuePrefix:
        enabled: true
        prefix: "app1_"
      putConfig:
        enabled: true
        numRuns: 500
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: false
            durationMs: 2000
            enableRandomness: true
          betweenActionBatches:
            enabled: true
            durationMs: 1000
            enableRandomness: true
          betweenRuns:
            enabled: true
            durationMs: 3500
            enableRandomness: true
      pollConfig:
        enabled: true
        numRuns: 500
        batchSize: 50
        sleeps:
          initialDelay:
            enabled: true
            durationMs: 20000
            enableRandomness: true
          betweenActionBatches:
            enabled: true
            durationMs: 1000
            enableRandomness: true
          betweenRuns:
            enabled: true
            durationMs: 3500
            enableRandomness: true

  maptests:
    pokedex:
      enabled: true
      numMaps: 10
      appendMapIndexToMapName: true
      appendClientIdToMapName: true
      numRuns: 10000
      mapPrefix:
        enabled: true
        prefix: "app1_"
      sleeps:
        betweenActionBatches:
          enabled: true
          durationMs: 3000
          enableRandomness: true
        betweenRuns:
          enabled: true
          durationMs: 5000
          enableRandomness: true
    load:
      enabled: true
      numMaps: 10
      numEntriesPerMap: 5000
      payloadSizeBytes: 1000000
      appendMapIndexToMapName: true
      appendClientIdToMapName: true
      numRuns: 10000
      mapPrefix:
        enabled: true
        prefix: "app1_"
      sleeps:
        betweenActionBatches:
          enabled: false
          durationMs: 200
          enableRandomness: true
        betweenRuns:
          enabled: false
          durationMs: 200
          enableRandomness: true